exp_name: ""
root_path: /Users/korea/OneDrive/바탕 화면/emotion_detector

data:
  folder_path: data
  train_file_name: train.csv
  eval_file_name: test.csv
  labels_file_name: labels.txt

model:
  name_or_path: "google/vit-base-patch16-224-in21k"

training_args:
  output_dir: "saved_models/"
  per_device_train_batch_size: 8
  evaluation_strategy: "steps"
  num_train_epochs: 4
  use_cpu: False
  save_steps: 1000
  eval_steps: 1000
  logging_steps: 10
  learning_rate: 2e-4
  save_total_limit: 2
  remove_unused_columns: False
  report_to: "tensorboard"
  load_best_model_at_end: True
